version: '4.5'

services:
  features:
    build: .
    ports:
      - "5254:5254"
    environment:
      GRPC_IPPORT: '0.0.0.0:5254'
      PSQL_URL: 'postgresql://postgres:postgres@features-postgres:5432/fichi'
      WAIT_HOSTS: features-postgres:5432 
  
  features-postgres:
    image: postgres:13.14-alpine3.19
    restart: always
    volumes:
      - features-pgdata:/var/lib/postgresql/data
    env_file:
      - .env.pg
    ports:
      - "5438:5432"

volumes:
  features-pgdata:
